# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7b92519eb2345c8904b251e7d6a849310cea4290afcde055da988a9d11428ff5c1c6cd9e33b98aab0701f45a5c32e0753ab1bf147415765ddde85c02664d981

test:
  secret_key_base: 7ab2f3809f04967d147507488b860cf571854c4c69ab1b0912f809c7f9722953bf38a1f476948586f993a1b513e66b3eeecba9cbb7935f74011a519700224231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
